name: merckfoundation22dec
description: A new Flutter project.

publish_to: "none"

version: 1.0.5

environment:
  sdk: ">=2.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  responsive_flutter: ^0.0.4
  carousel_slider: ^2.3.1
  dots_indicator: ^1.2.0
  flutter_swiper: ^1.1.6
  bottom_navy_bar: ^5.5.0
  marquee: ^1.6.1
  animated_widgets: ^1.0.6
  animations: ^1.1.2
  flutter_staggered_animations: ^0.1.2
  photo_view: ^0.10.2
  youtube_player_flutter:
  file: ^6.1.4
  url_launcher:
  flutter_pagewise: ^1.2.3
  http: ^0.12.2
  adv_fab: ^1.0.5
  bubble_tab_indicator: ^0.1.4
  flutter_spinkit: ^4.1.2+1
  screenshot: ^0.1.1
  flutter_custom_clippers: ^1.1.2
  connectivity:
  flip_card:
  intl:
  shared_preferences:
  package_info: ^2.0.2
  firebase_analytics:
  firebase_core:
  device_info: ^2.0.2
  path_provider:
  permission_handler:
  flutter_html: ^2.2.1
  device_apps:
  flutter_widget_from_html:
  launch_review: ^3.0.1
  fluttertoast: ^8.2.5
  chewie: ^1.3.3
  wakelock: ^0.6.2
  flutter_local_notifications:
  firebase_remote_config: ^2.0.0
  firebase_messaging:
  # platform: 3.0.0
  social_share_plugin: ^0.4.1+2
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/newImages/ic_launcher.png"
  android: true
  ios: true

dependency_overrides:
  plugin_platform_interface: 2.1.3
  firebase_core_platform_interface: 4.5.1

# For information on the generic Dart part of this file, see the following page:
# https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/newImages/
    - assets/API-Configuration.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product Sans Bold Italic.ttf
        - asset: assets/fonts/Product Sans Bold.ttf
        - asset: assets/fonts/Product Sans Italic.ttf
        - asset: assets/fonts/Product Sans Regular.ttf

    - family: verdana
      fonts:
        - asset: assets/fonts/Verdana Bold.ttf
        - asset: assets/fonts/Verdana.ttf
        - asset: assets/fonts/verdanab.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
