# name: merckfoundation22dec
# description: A new Flutter project.
# publish_to: "none"
# version: 1.0.5

# environment:
#   sdk: ">=3.0.0 <4.0.0"

# dependencies:
#   flutter:
#     sdk: flutter
#   cupertino_icons: ^1.0.6
#   # responsive_flutter: ^0.0.4
#   carousel_slider: ^4.2.1
#   dots_indicator: ^3.0.0
#   card_swiper: ^3.0.1 # replaces flutter_swiper
#   bottom_navy_bar: ^6.0.0
#   marquee: ^2.2.0
#   animated_widgets: ^1.1.0
#   animations: ^2.0.7
#   flutter_staggered_animations: ^1.1.0
#   photo_view: ^0.14.0
#   file: ^6.1.4
#   url_launcher: ^6.2.6
#   flutter_pagewise: ^2.0.1
#   http: ^1.2.1
#   # adv_fab:
#     # ^1.0.5
#   bubble_tab_indicator: ^0.1.6
#   flutter_spinkit: ^5.1.0
#   screenshot: ^1.3.0
#   flutter_custom_clippers: ^2.0.0
#   connectivity_plus: ^4.0.2 # updated
#   flip_card: ^0.7.0
#   intl: ^0.18.1
#   shared_preferences: ^2.2.2
#   # package_info_plus: ^5.0.1 # replaces package_info
#   firebase_analytics: ^10.10.0
#   firebase_core: ^2.17.0
#   device_info_plus: ^9.0.3 # replaces device_info
#   path_provider: ^2.1.3
#   permission_handler: ^11.3.0
#   flutter_html: ^3.0.0
#   device_apps: ^2.2.0
#   flutter_widget_from_html: ^0.10.5
#   launch_review: ^3.0.1
#   fluttertoast: ^8.2.5
#   chewie: ^1.7.4
#   wakelock: 
#   wakelock_plus: 1.2.4

#   # ^0.6.2
#   firebase_messaging: ^14.7.10
#   flutter_local_notifications: ^17.0.0
#   firebase_remote_config: ^4.2.5
  
#   plugin_platform_interface: ^2.1.6
#   webview_flutter: ^4.7.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

# dependency_overrides:
#   collection: ^1.19.0


# flutter_icons:
#   image_path: "assets/newImages/ic_launcher.png"
#   android: true
#   ios: true

# flutter:
#   uses-material-design: true

#   assets:
#     - assets/images/
#     - assets/newImages/
#     - assets/API-Configuration.json

#   fonts:
#     - family: Product Sans
#       fonts:
#         - asset: assets/fonts/Product Sans Bold Italic.ttf
#         - asset: assets/fonts/Product Sans Bold.ttf
#         - asset: assets/fonts/Product Sans Italic.ttf
#         - asset: assets/fonts/Product Sans Regular.ttf

#     - family: verdana
#       fonts:
#         - asset: assets/fonts/Verdana Bold.ttf
#         - asset: assets/fonts/Verdana.ttf
#         - asset: assets/fonts/verdanab.ttf


name: merckfoundation22dec

description: A new Flutter project.

publish_to: "none"

version: 1.0.36

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  # social_share: ^2.3.1
  # responsive_flutter: 
  carousel_slider: 
  dots_indicator: 
  # flutter_swiper: ^1.1.6
  bottom_navy_bar: 
  marquee: 
  animated_widgets: 
  animations: 
  flutter_staggered_animations: 
  photo_view: 
  # youtube_player_flutter:
  file: 
  url_launcher:
  flutter_pagewise: 
  http: 
  # adv_fab: 
  bubble_tab_indicator: 0.1.6
  flutter_spinkit: 
  screenshot: 
  flutter_custom_clippers: 
  connectivity:
  flip_card:
  intl:
  shared_preferences:
  package_info: 
  firebase_analytics:
  
  device_info: 
  path_provider:
  permission_handler:
  flutter_html: 
  device_apps:
  flutter_widget_from_html:
  launch_review: 
  fluttertoast: 
  chewie: 
  # wakelock: 
  # wakelock_windows: ^0.2.0+1
  flutter_local_notifications: 15.1.1
  firebase_remote_config: 
  youtube_player_flutter: 
  # win32: 3.0.0
  
  # platform: 3.0.0
  # social_share_plugin: ^0.4.1+2
  
  
  plugin_platform_interface: 
  webview_flutter: ^3.0.4
  firebase_core: 2.25.4
  firebase_messaging: 14.7.10
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/newImages/ic_launcher.png"
  android: true
  ios: true

dependency_overrides:
  plugin_platform_interface: 2.1.3
  # firebase_core_platform_interface: 4.5.1
  

# For information on the generic Dart part of this file, see the following page:
# https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/newImages/
    - assets/API-Configuration.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product Sans Bold Italic.ttf
        - asset: assets/fonts/Product Sans Bold.ttf
        - asset: assets/fonts/Product Sans Italic.ttf
        - asset: assets/fonts/Product Sans Regular.ttf

    - family: verdana
      fonts:
        - asset: assets/fonts/Verdana Bold.ttf
        - asset: assets/fonts/Verdana.ttf
        - asset: assets/fonts/verdanab.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
